// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoBulaFinal.Repositorio.Entity;

#nullable disable

namespace ProjetoBulaFinal.Migrations
{
    [DbContext(typeof(BulaContexto))]
    partial class BulaContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoBulaFinal.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("CNAE")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CNAE");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CPF");

                    b.Property<string>("CRF")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CRF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Permissao");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Senha");

                    b.Property<string>("VISA")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("VISA");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("ProjetoBulaFinal.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ativo");

                    b.Property<string>("Consumidor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Consumidor");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EAN");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Forma");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("RMS")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RMS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Unidade");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Via");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
